/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWorkspaceIdIndexRouteImport } from './routes/w/$workspaceId/index'
import { Route as WWorkspaceIdHistoryRouteImport } from './routes/w/$workspaceId/history'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdIndexRoute = WWorkspaceIdIndexRouteImport.update({
  id: '/w/$workspaceId/',
  path: '/w/$workspaceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdHistoryRoute = WWorkspaceIdHistoryRouteImport.update({
  id: '/w/$workspaceId/history',
  path: '/w/$workspaceId/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/w/$workspaceId/history': typeof WWorkspaceIdHistoryRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/w/$workspaceId/history': typeof WWorkspaceIdHistoryRoute
  '/w/$workspaceId': typeof WWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/w/$workspaceId/history': typeof WWorkspaceIdHistoryRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/w/$workspaceId/history' | '/w/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/w/$workspaceId/history' | '/w/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/w/$workspaceId/history'
    | '/w/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  WWorkspaceIdHistoryRoute: typeof WWorkspaceIdHistoryRoute
  WWorkspaceIdIndexRoute: typeof WWorkspaceIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/': {
      id: '/w/$workspaceId/'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof WWorkspaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/history': {
      id: '/w/$workspaceId/history'
      path: '/w/$workspaceId/history'
      fullPath: '/w/$workspaceId/history'
      preLoaderRoute: typeof WWorkspaceIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  WWorkspaceIdHistoryRoute: WWorkspaceIdHistoryRoute,
  WWorkspaceIdIndexRoute: WWorkspaceIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
